apiVersion: v1
kind: Template
metadata:
  name: inventory-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: inventory
    spec:
      envName: ${ENV_NAME}
      title: Inventory
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/inventory
      image: quay.io/cloudservices/insights-inventory-frontend:a82f241
      navItems:
        - appId: "inventory"
          title: "Inventory"
          href: "/insights/inventory"
          product: "Red Hat Insights"
      module:
        manifestLocation: "/apps/inventory/fed-mods.json"
        modules:
          - id: "inventory"
            module: "./RootApp"
            routes:
              - pathname: /insights/inventory

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: INVENTORY_IMAGE
    value: quay.io/cloudservices/insights-inventory-frontend
